In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Paso 1- Filtro por filas (0-673)

In [13]:
#NOTA: el Excel marca cada mes con una fila separadora (ej. "MAYO", "JUNIO" o una fecha 01/01/2026).
#El bloque de Julio 2026 termina hasta la fila 687 del Excel (indice 685 del DataFrame),
#por lo que se ajusta el corte de 0:673 a 0:686 para no perder registros de Julio 2026.
filtro1 = df.iloc[0:686, :]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       670 non-null    object
 1   Fecha                                     85 non-null     datetime64[us]
 2   Nombre Cliente                            665 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           651 non-null    object
 5   Potencial de compra                       611 non-null    object
 6   PDM                                       685 non-null    float64
 7   SDC                                       684 non-null    float64
 8   Venta                                     681 non-null    float64
 9   Asesor Asignado                           653 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 85.9+ KB

Paso 2- Filtro por columnas (0,1,2,4,5,6,7,8,9)

In [14]:
filtro2 = df.iloc[:, [0, 1, 2, 4, 5, 6, 7, 8, 9]]
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 9 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   BDC                  673 non-null      object
 1   Fecha                88 non-null       datetime64[us]
 2   Nombre Cliente       668 non-null      object
 3   Estatus de Lead      654 non-null      object
 4   Potencial de compra  614 non-null      object
 5   PDM                  1048574 non-null  float64
 6   SDC                  1048573 non-null  float64
 7   Venta                1048570 non-null  float64
 8   Asesor Asignado      656 non-null      str
dtypes: datetime64[us](1), float64(3), object(4), str(1)
memory usage: 72.0+ MB

In [15]:
filtro3 = df.iloc[0:686, [0, 1, 2, 4, 5, 6, 7, 8, 9]]
filtro3.info()

<class 'pandas.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  670 non-null    object
 1   Fecha                85 non-null     datetime64[us]
 2   Nombre Cliente       665 non-null    object
 3   Estatus de Lead      651 non-null    object
 4   Potencial de compra  611 non-null    object
 5   PDM                  685 non-null    float64
 6   SDC                  684 non-null    float64
 7   Venta                681 non-null    float64
 8   Asesor Asignado      653 non-null    str
dtypes: datetime64[us](1), float64(3), object(4), str(1)
memory usage: 48.4+ KB

In [16]:
filtro3.to_csv("Citas_Digital_Filtrado.csv", index=False)

In [17]:
df_filtrado = pd.read_csv("Citas_Digital_Filtrado.csv")
df_filtrado.info()

<class 'pandas.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  670 non-null    str
 1   Fecha                85 non-null     str
 2   Nombre Cliente       665 non-null    str
 3   Estatus de Lead      651 non-null    str
 4   Potencial de compra  611 non-null    str
 5   PDM                  685 non-null    float64
 6   SDC                  684 non-null    float64
 7   Venta                681 non-null    float64
 8   Asesor Asignado      653 non-null    str
dtypes: float64(3), str(6)
memory usage: 48.4 KB

In [18]:
df_filtrado_indice = pd.read_csv("Citas_Digital_Filtrado.csv", index_col=8)
df_filtrado_indice

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta
Asesor Asignado,,,,,,,,
Nancy,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0
Victor,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0
Alan,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0
Mauricio,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0
Mauricio,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
Pedro Antonio,Ana,2026-07-23,Ruben Dario,Activo,0.9,1.0,1.0,0.0
Nayeli,Ignacio,2026-07-30,Jesus Torres,Activo,0.7,1.0,1.0,0.0
Nayeli,Ignacio,2026-09-29,Arquimedes Rugerio,Activo,NaN,0.0,1.0,0.0
Carlos,Ana,2026-07-30,Jorge Hernandez,Activo,0.5,0.0,0.0,0.0
NaN,Ignacio,2026-07-28,Zabdiel Medrano,Activo,0.8,1.0,1.0,0.0

Paso 3- Convertir los datos de la variable “Potencial de compra” a tipo float

In [19]:
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].astype(str)
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].str.replace("Ventas ", "0", regex=False)
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].str.replace("%", "", regex=False)
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].str.replace("'", "", regex=False)
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].str.replace("&", "", regex=False)
df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].replace("nan", np.nan)

df_filtrado['Potencial de compra'] = df_filtrado['Potencial de compra'].astype(float)
df_filtrado.info()

<class 'pandas.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  670 non-null    str
 1   Fecha                85 non-null     str
 2   Nombre Cliente       665 non-null    str
 3   Estatus de Lead      651 non-null    str
 4   Potencial de compra  611 non-null    float64
 5   PDM                  685 non-null    float64
 6   SDC                  684 non-null    float64
 7   Venta                681 non-null    float64
 8   Asesor Asignado      653 non-null    str
dtypes: float64(4), str(5)
memory usage: 48.4 KB

Paso 4- Obtener el CSV General y nombrarlo “Citas_Digital_General.csv”

In [20]:
df_filtrado.to_csv("Citas_Digital_General.csv", index=False)

Paso 5- A partir del archivo “Citas_Digital_General.csv” realizar un filtro por filas para obtener un archivo .csv por cada mes (Desde abril 2025 hasta julio 2026) y nombrarlos con el mes y año correspondiente ejemplo: “Abril_2025.csv” (16 entregables)

In [21]:
df_general = pd.read_csv("Citas_Digital_General.csv")

#Rangos de filas segun las filas marcadoras de cada mes en el Excel original
#(fila_inicio, fila_fin) son indices de df_general (ya excluyen filas marcadoras y filas vacias)
rangos_meses = [
    ("Abril",      "2025", 0,   30),
    ("Mayo",       "2025", 34,  58),
    ("Junio",      "2025", 61,  86),
    ("Julio",      "2025", 88,  120),
    ("Agosto",     "2025", 122, 166),
    ("Septiembre", "2025", 168, 230),
    ("Octubre",    "2025", 232, 290),
    ("Noviembre",  "2025", 292, 343),
    ("Diciembre",  "2025", 345, 391),
    ("Enero",      "2026", 393, 428),
    ("Febrero",    "2026", 430, 460),
    ("Marzo",      "2026", 462, 477),
    ("Abril",      "2026", 479, 533),
    ("Mayo",       "2026", 540, 598),
    ("Junio",      "2026", 600, 640),
    ("Julio",      "2026", 642, 685),
]

In [22]:
for mes, anio, fila_ini, fila_fin in rangos_meses:
    #Filtro por filas: seleccionamos el bloque de filas correspondiente al mes
    filtro_mes = df_general.iloc[fila_ini:fila_fin + 1]

    filtro_mes.to_csv(f"{mes}_{anio}.csv", index=False)
    print(f"{mes}_{anio}.csv -> {len(filtro_mes)} filas")

Abril_2025.csv -> 31 filas
Mayo_2025.csv -> 25 filas
Junio_2025.csv -> 26 filas
Julio_2025.csv -> 33 filas
Agosto_2025.csv -> 45 filas
Septiembre_2025.csv -> 63 filas
Octubre_2025.csv -> 59 filas
Noviembre_2025.csv -> 52 filas
Diciembre_2025.csv -> 47 filas
Enero_2026.csv -> 36 filas
Febrero_2026.csv -> 31 filas
Marzo_2026.csv -> 16 filas
Abril_2026.csv -> 55 filas
Mayo_2026.csv -> 59 filas
Junio_2026.csv -> 41 filas
Julio_2026.csv -> 44 filas